apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: jenkins
spec:
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP